from constructs import Construct
#
# Provider bindings are generated by running `cdktf get`.
# See https://cdk.tf/provider-generation for more details.
#
from imports.digitalocean.kubernetes_cluster import KubernetesCluster
class MyConvertedCode(Construct):
    def __init__(self, scope, name):
        super().__init__(scope, name)
        # The following providers are missing schema information and might need manual adjustments to synthesize correctly: digitalocean.
        #     For a more precise conversion please use the --provider flag in convert.
        KubernetesCluster(self, "kubernetes_cluster",
            name="longe-cluster",
            node_pool=[{
                "auto_scale": True,
                "max_nodes": 5,
                "min_nodes": 1,
                "name": "db-pool",
                "node_count": 1,
                "size": "s-2vcpu-4gb",
                "tags": ["db-nodes"]
            }
            ],
            region="eu-west-2",
            version="1.23"
        )
